icon/chainscore.go, icon/chainscore_basic.go, icon/revision.go
Add governance functions to chainscore
=> IC2-34: Add governance functions to chainscore

icon/iiss/icstate/networkvalue.go, icon/iiss/icstate/term.go, icon/iiss/icstate/term_test.go, icon/iiss/icstate/termcache.go
- apply configuration for term period
=> add term period configuration

icon/chainscore.go, icon/chainscore_iiss.go, icon/iiss/icstate/networkvalue.go, icon/iiss/iiss_variables.go
* set lockMin, lockMax at genesisBlock with config values
=> IC2-49: Add config values for lockMin, lockMax

icon/iiss/icstate/networkValue_test.go, icon/iiss/icstate/networkvalue.go
* fix setLockMax function
* modify signature of State.SetBondRequirement
* Add unit tests for networkValues
=> IC2-60: fix networkvalue bugs

icon/chainscore.go, icon/chainscore_iiss.go, icon/iiss/extension.go, icon/iiss/icstate/networkvalue.go, icon/iiss/icstate/prepbase_test.go, icon/iiss/icstate/prepstatus.go, icon/iiss/icstate/state.go, icon/iiss/icstate/term.go, icon/iiss/icstate/term_test.go, icon/iiss/icstate/termcache.go, icon/iiss/issuer.go, icon/iiss/prepmanager.go
- Add rrep to Term
- Add 'getNetworkValue' JSON-RPC API for testing
- Fix Term.newNextTerm() to read irep, rrep and period from networkValue
=> Add GetTotalBondedDelegation() to Term

icon/iiss/icstate/account.go, icon/iiss/icstate/account_test.go, icon/iiss/icstate/bond.go, icon/iiss/icstate/bond_test.go, icon/iiss/icstate/delegation.go, icon/iiss/icstate/delegation_test.go, icon/iiss/icstate/unstake.go
* fix GetUnbondingInfo method.
- move diff into for loop to clear value
- set uDiff to adjusted value, unbonding value when unbonding Value < 0
* fix NewBonds, NewDelegations
- prohibit set bond/delegation value to negative value
=> IC2-66: fix account bugs

icon/chainscore.go, icon/chainscore_iiss.go, icon/iiss/extension.go, icon/iiss/icstate/account.go, icon/iiss/icstate/networkvalue.go, icon/iiss/icstate/networkvalue_test.go, icon/iiss/icstate/prepstatus.go, icon/iiss/icstate/state.go, icon/iiss/icstate/term.go, icon/iiss/issuer.go, icon/iiss/prepmanager.go
networkvalue registered as members of state. 
apply terminology according to the definition.
IISS setStake bug fixed.
=> networkvalue registered as members of state. 

.github/workflows/pull_request.yml, .gitignore
Add github action configuration for CI
=> IC2-48: Add github action configuration for CI

icon/iiss/icstate/account.go, icon/iiss/icstate/account_test.go, icon/iiss/icstate/unbond.go, icon/iiss/icstate/unbond_test.go, icon/iiss/penalty.go
* slash stake, update totalStake in Slash method
* remove unbondings if ratio == 100
* remove unbondingTimer element when ratio == 100
=> IC2-44: fix Slash

icon/chainscore_iiss.go, icon/iiss/extension.go, icon/iiss/icstate/state.go, icon/iiss/penalty.go, icon/iiss/prepmanager.go, icon/iiss/timerhandler.go
- add createIfNotExist option to GetTimer, as cache policy changed
=> change reflected along with cache policy change

icon/chainscore.go, icon/iiss/extension.go, icon/iiss/icstate/networkvalue.go
* Set default unbondingPeriod to 7terms
* enable to set unbonding period
=> IC2-77: set default unbonding period to 7terms

icon/chainscore.go, icon/chainscore_iiss.go, icon/iiss/icstate/account.go, icon/iiss/icstate/account_test.go, icon/iiss/icstate/networkvalue.go, icon/iiss/icstate/networkvalue_test.go, icon/iiss/icstate/state.go, icon/iiss/icstate/unstake.go, icon/iiss/icstate/unstake_test.go
* read unstakeSlotMax from config file
* add networkvalue for unstakeSlotMax
=> IC2-78: enable to set unstakeSlotMax

icon/iiss/icstate/account.go, icon/iiss/icstate/account_test.go
=> IC2-86: Fix GetVoting method

icon/iiss/base.go, icon/platform.go
Process timer jobs on ExecutionEnd not on base tx
=> IC2-87: handle timer jobs on executionEnd

icon/iiss/icstate/account.go, icon/iiss/icstate/unstake.go, icon/iiss/icstate/unstake_test.go
remove previous unstaking timer if unstake modified
=> IC2-88: fix setStake bug

icon/chainscore.go, icon/chainscore_basic.go, icon/chainscore_iiss.go, icon/iiss/extension.go
add disqualifyPRep, validateIRep
=> IC2-40: Add chainscore methods for systemScoreBase

icon/iiss/timerhandler.go
print log when processing timer
=> IC2-115: print log when processing timer

icon/chainscore.go, icon/chainscore_iiss.go, icon/icmodule/revision.go, icon/iiss/icutils/utils.go, icon/iiss/icutils/utils_test.go, icon/iiss/penalty.go
- modify ICXBurned event log
- add external method 'burn' to chainscore
=> Migrate FIX_BURN_EVENT_SIGNATURE

icon/chainscore.go, icon/chainscore_basic.go, icon/chainscore_iiss.go, icon/icmodule/revision.go, icon/iiss/icstate/account.go, icon/iiss/icstate/unstake.go, icon/iiss/icstate/unstake_test.go
=> Implement single unstakes

icon/iiss/icstate/account.go, icon/iiss/icstate/account_test.go, icon/iiss/icstate/accountcache.go, icon/iiss/icstate/accountcache_test.go, icon/iiss/icstate/object.go
* remove address from account struct.
=> Remove address from icstate.Account

icon/iiss/icstate/account.go, icon/iiss/icstate/account_test.go, icon/iiss/icstate/unbond.go, icon/iiss/icstate/unbond_test.go, icon/iiss/icstate/unstake.go, icon/iiss/icstate/unstake_test.go
=> IC2-174: encapsulate Unbond and Unstake

icon/iiss/icstate/account_test.go, icon/iiss/icstate/unstake.go
* ExpireHeight of last unstake will take max(prevUnstakeHeight, newUnstakeHeight) not newUnstakeHeight
=> Fix increaseUnstake

icon/chainscore_iiss.go, icon/iiss/extension.go
* Check owner on setNetworkScore
* slash after impose penalty
=> IC-158: Network Score management

icon/chainscore.go, icon/chainscore_basic.go, icon/chainscore_iiss.go, icon/iiss/extension.go, icon/iiss/icstate/networkvalue.go
* validate integer param range
* revert min version of penalizeNonvoters
=> Fix chainscore methods

icon/chainscore_iiss.go
* handle nil value
* invalidParamError -> illegalArgumentError
=> Fix setNetworkScore

icon/chainscore_iiss.go
* SlashingRateChanged(string,int) -> SlashingRateChanged(str,int)
* Refactor code
=> Fix SlashingRateChanged eventLog signature

.github/workflows/go_test.yml
go test with go version `1.17.8`
=> Upgrade go version to 1.17.8 in github action

doc/iiss_extension.md, icon/chainscore_btp.go, icon/chainscore_iiss.go, icon/icsim/simulator_test.go, icon/icsim/simulatorimpl.go, icon/iiss/extension.go, icon/iiss/icstate/networkvalue.go, icon/iiss/icstate/prep.go, icon/iiss/icstate/prep_test.go, icon/iiss/icstate/prepstatus.go, icon/iiss/icstate/prepstatus_test.go, icon/iiss/icstate/state.go, icon/iiss/icstate/term.go
- Sort getPReps result by Public key and Power
- Update getPReps in iiss_extension.md
=> Fix getPReps

icon/iiss/icstate/issue.go, icon/iiss/icstate/issue_test.go
* Reduce the number of memory allocation
* Add unit-tests
=> Optimize icstate/issue.go

icon/icmodule/revision.go, icon/iiss/icreward/iscore.go, icon/iiss/icreward/iscore_test.go
=> BugFix IScore.Subtracted()

icon/iiss/icstate/prepcache.go
Cache last PRepStatus to reduce write operations to database
=> Optimize PRepStatusCache

doc/icon_chainscore_api.md, icon/chainscore.go, icon/chainscore_iiss.go, icon/icmodule/revision.go, icon/iiss/icstate/prepstatus.go, icon/iiss/icstate/prepstatus_test.go, icon/iiss/icstate/state.go
* Add owner field to the response of getPRepStats() API after RevisionUpdatePRepStats(22)
* Introduce getPRepStatsOf(address Address) after RevisionUpdatePRepStats(22)
* Return AccessDenied error when calling getPRepStats in a transaction
=> Update getPRepStats API

icon/chainscore.go, icon/chainscore_basic.go, icon/chainscore_iiss.go, icon/icmodule/revision.go, icon/icsim/simulatorimpl.go, icon/iiss/extension.go, icon/iiss/icstage/global.go, icon/iiss/icstage/global_test.go, icon/iiss/icstage/state.go, icon/iiss/icstate/networkvalue.go, icon/iiss/icstate/networkvalue_test.go, icon/iiss/icstate/rewardfund.go, icon/iiss/icstate/rewardfund_test.go, icon/iiss/icstate/state_test.go, icon/iiss/icstate/term.go, icon/iiss/icstate/term_test.go, icon/iiss/rewards/iiss4/reward.go, icon/iiss/rewards/iiss4/reward_test.go
- Activated at RevisionPreIISS4
- Configure icstate.RewardFund2
- Add Term Version2
- since RevisionIISS4
- add icstate.RewardFund2
- Add GlobalV3 to icstage with termVersion2 data since RevsionIISS4
=> Add chainScore.setRewardFundAllocation2

icon/chainscore.go, icon/chainscore_basic.go, icon/chainscore_iiss.go, icon/icsim/revision.go, icon/iiss/extension.go, icon/iiss/icstage/global.go, icon/iiss/icstage/global_test.go, icon/iiss/icstage/state.go, icon/iiss/icstate/networkvalue.go, icon/iiss/icstate/networkvalue_test.go, icon/iiss/icstate/rewardfund.go, icon/iiss/icstate/rewardfund_test.go, icon/iiss/icstate/term.go, icon/iiss/icstate/term_test.go, icon/iiss/rewards/iiss4/reward_test.go
- Add RewardFund interface
- Fix Ex_setRewardFund() to set RewardFund1 and RewardFund2 at RevisionPreIISS4
- Fix functions to support RewardFund2
- ValidateRewardFund()
- transferRewardFund()
=> Fix reward fund handling

icon/chainscore.go, icon/chainscore_iiss.go, icon/iiss/eventlog.go, icon/iiss/extension.go, icon/iiss/extension_test.go, icon/iiss/icstate/commissioninfo.go, icon/iiss/icstate/commissioninfo_test.go, icon/iiss/icstate/prepbase.go, icon/iiss/icstate/prepbase_test.go, icon/iiss/icstate/state.go, icon/iiss/icstate/state_test.go
* Introduce CommissionInfo structure
* Implement initCommissionRate API
* Implement setCommissionRate API
* Introduce CommissionRateInitialized(Address,int,int,int), CommissionRateChanged(Address,int) eventLogs
=> Implement CommissionRate related APIs of ChainScore

icon/icmodule/context.go, icon/icsim/context.go, icon/icsim/simulator_test.go, icon/icsim/simulatorimpl.go, icon/iiss/base.go, icon/iiss/context.go, icon/iiss/extension.go, icon/iiss/icstate/jailinfo.go, icon/iiss/icstate/jailinfo_test.go, icon/iiss/icstate/prep.go, icon/iiss/icstate/prep_test.go, icon/iiss/icstate/prepstatus.go, icon/iiss/icstate/prepstatus_test.go, icon/iiss/icstate/state.go, icon/iiss/icstate/state_test.go, icon/iiss/icstate/term.go, icon/iiss/penalty.go, icon/iiss/statecontext.go
* Add GetActiveDSAMask() to icmodule.StateContext interface
* Move stateContext struct to iiss package
* Fix issues caused by StateContext refactoring
=> Refactor StateContext in icon platform

icon/iiss/icreward/voted.go, icon/iiss/icreward/voted_test.go, icon/iiss/rewards/iiss3.go
- update Voted.version to VotedVersion2 with Voted.SetCommissionRate()
=> Fix updating commission rate of Voted in Rev23

icon/icmodule/revision.go, icon/icsim/revision.go, icon/revision.go
* RevisionPreIISS4: 23 -> 22
* RevisionIISS4: 24 -> 23
=> IISS4 Revision Change

doc/icon_chainscore_api.md, icon/chainscore_iiss.go, icon/icmodule/revision.go, icon/iiss/eventlog.go, icon/iiss/extension.go, icon/iiss/rewards/iiss4/prep.go, icon/iiss/rewards/iiss4/voter.go, icon/iiss/rewards/iiss4/voter_test.go
* ~~SetBond(Address,bytes)~~ -> BondSet(Address,bytes)
* ~~SetDelegation(Address,bytes)~~ -> Delegation(Address,bytes)
=> Add vote event log

icon/iiss/calculator/iiss4.go, icon/iiss/calculator/iiss4_test.go, icon/iiss/calculator/prep.go, icon/iiss/calculator/prep_test.go, icon/iiss/calculator/voter_test.go
- calculate accumulated power of PRep with voted and bonded whenever voted and bonded values change
- remove PRep.accumulatedBonded
=> Improve accumulated power calculation

doc/icon_chainscore_api.md, icon/chainscore.go, icon/chainscore_basic.go, icon/chainscore_iiss.go, icon/chainscore_test.go, icon/governancehandler.go, icon/icmodule/revision.go, icon/iiss/eventlog.go, icon/iiss/eventlog_test.go, icon/iiss/icstate/rewardfund.go, icon/iiss/icstate/rewardfund_test.go
- RevisionSet(int)
- StepPriceSet(int)
- StepCostSet(String,int)
- MaxStepLimitSet(str,int)
- ~~ContractBlockedSet(Address,bool)~~
- RewardFundSet(int)
- RewardFundAllocationSet(str,int)
- NetworkScoreSet(str,Address)
=> Add event logs
